apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tls-ingress
spec:
  tls:
  - secretName: {{.Values.tlssecretname}}
  backend:
    serviceName: {{.Values.lbservicename}}
    servicePort: 80
